spring:
  application:
    name: full-stack-project-backend
  datasource:
    url: jdbc:mysql://localhost:3306/gforo
    username: root
    password: 123456
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create
    show-sql: on
    properties:
      hibernate.hibernate.format_sql: true

logging:
  level:
    root: info
  file:
    name: logs/application.log